php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaa &> /1/ximm_tmp/graph/logs/xaa.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xab &> /1/ximm_tmp/graph/logs/xab.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xac &> /1/ximm_tmp/graph/logs/xac.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xad &> /1/ximm_tmp/graph/logs/xad.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xae &> /1/ximm_tmp/graph/logs/xae.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaf &> /1/ximm_tmp/graph/logs/xaf.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xag &> /1/ximm_tmp/graph/logs/xag.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xah &> /1/ximm_tmp/graph/logs/xah.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xai &> /1/ximm_tmp/graph/logs/xai.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaj &> /1/ximm_tmp/graph/logs/xaj.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xak &> /1/ximm_tmp/graph/logs/xak.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xal &> /1/ximm_tmp/graph/logs/xal.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xam &> /1/ximm_tmp/graph/logs/xam.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xan &> /1/ximm_tmp/graph/logs/xan.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xao &> /1/ximm_tmp/graph/logs/xao.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xap &> /1/ximm_tmp/graph/logs/xap.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaq &> /1/ximm_tmp/graph/logs/xaq.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xar &> /1/ximm_tmp/graph/logs/xar.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xas &> /1/ximm_tmp/graph/logs/xas.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xat &> /1/ximm_tmp/graph/logs/xat.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xau &> /1/ximm_tmp/graph/logs/xau.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xav &> /1/ximm_tmp/graph/logs/xav.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaw &> /1/ximm_tmp/graph/logs/xaw.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xax &> /1/ximm_tmp/graph/logs/xax.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xay &> /1/ximm_tmp/graph/logs/xay.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xaz &> /1/ximm_tmp/graph/logs/xaz.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xba &> /1/ximm_tmp/graph/logs/xba.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbb &> /1/ximm_tmp/graph/logs/xbb.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbc &> /1/ximm_tmp/graph/logs/xbc.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbd &> /1/ximm_tmp/graph/logs/xbd.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbe &> /1/ximm_tmp/graph/logs/xbe.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbf &> /1/ximm_tmp/graph/logs/xbf.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbg &> /1/ximm_tmp/graph/logs/xbg.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbh &> /1/ximm_tmp/graph/logs/xbh.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbi &> /1/ximm_tmp/graph/logs/xbi.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbj &> /1/ximm_tmp/graph/logs/xbj.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbk &> /1/ximm_tmp/graph/logs/xbk.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbl &> /1/ximm_tmp/graph/logs/xbl.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbm &> /1/ximm_tmp/graph/logs/xbm.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbn &> /1/ximm_tmp/graph/logs/xbn.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbo &> /1/ximm_tmp/graph/logs/xbo.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbp &> /1/ximm_tmp/graph/logs/xbp.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbq &> /1/ximm_tmp/graph/logs/xbq.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbr &> /1/ximm_tmp/graph/logs/xbr.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbs &> /1/ximm_tmp/graph/logs/xbs.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbt &> /1/ximm_tmp/graph/logs/xbt.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbu &> /1/ximm_tmp/graph/logs/xbu.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=3000 --ldpath=/1/ximm_tmp/graph/xbv &> /1/ximm_tmp/graph/logs/xbv.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=1454 --ldpath=/1/ximm_tmp/graph/xbw &> /1/ximm_tmp/graph/logs/xbw.log &
ps fauxwww | grep /home/ximm/projects/search/listerine/es_indexer.php
