php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaa &> /1/ximm_tmp/cut/logs/xaa.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xab &> /1/ximm_tmp/cut/logs/xab.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xac &> /1/ximm_tmp/cut/logs/xac.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xad &> /1/ximm_tmp/cut/logs/xad.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xae &> /1/ximm_tmp/cut/logs/xae.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaf &> /1/ximm_tmp/cut/logs/xaf.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xag &> /1/ximm_tmp/cut/logs/xag.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xah &> /1/ximm_tmp/cut/logs/xah.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xai &> /1/ximm_tmp/cut/logs/xai.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaj &> /1/ximm_tmp/cut/logs/xaj.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xak &> /1/ximm_tmp/cut/logs/xak.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xal &> /1/ximm_tmp/cut/logs/xal.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xam &> /1/ximm_tmp/cut/logs/xam.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xan &> /1/ximm_tmp/cut/logs/xan.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xao &> /1/ximm_tmp/cut/logs/xao.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xap &> /1/ximm_tmp/cut/logs/xap.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaq &> /1/ximm_tmp/cut/logs/xaq.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xar &> /1/ximm_tmp/cut/logs/xar.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xas &> /1/ximm_tmp/cut/logs/xas.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xat &> /1/ximm_tmp/cut/logs/xat.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xau &> /1/ximm_tmp/cut/logs/xau.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xav &> /1/ximm_tmp/cut/logs/xav.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaw &> /1/ximm_tmp/cut/logs/xaw.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xax &> /1/ximm_tmp/cut/logs/xax.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xay &> /1/ximm_tmp/cut/logs/xay.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xaz &> /1/ximm_tmp/cut/logs/xaz.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xba &> /1/ximm_tmp/cut/logs/xba.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbb &> /1/ximm_tmp/cut/logs/xbb.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbc &> /1/ximm_tmp/cut/logs/xbc.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbd &> /1/ximm_tmp/cut/logs/xbd.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbe &> /1/ximm_tmp/cut/logs/xbe.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbf &> /1/ximm_tmp/cut/logs/xbf.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbg &> /1/ximm_tmp/cut/logs/xbg.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbh &> /1/ximm_tmp/cut/logs/xbh.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbi &> /1/ximm_tmp/cut/logs/xbi.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbj &> /1/ximm_tmp/cut/logs/xbj.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbk &> /1/ximm_tmp/cut/logs/xbk.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbl &> /1/ximm_tmp/cut/logs/xbl.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbm &> /1/ximm_tmp/cut/logs/xbm.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbn &> /1/ximm_tmp/cut/logs/xbn.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbo &> /1/ximm_tmp/cut/logs/xbo.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbp &> /1/ximm_tmp/cut/logs/xbp.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbq &> /1/ximm_tmp/cut/logs/xbq.log2 &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=80000 --ldpath=/1/ximm_tmp/cut/xbr &> /1/ximm_tmp/cut/logs/xbr.log2 &
ps fauxwww | grep /home/ximm/projects/search/listerine/es_indexer.php
