php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaa &> /1/ximm_tmp/cut/logs/xaa.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xab &> /1/ximm_tmp/cut/logs/xab.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xac &> /1/ximm_tmp/cut/logs/xac.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xad &> /1/ximm_tmp/cut/logs/xad.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xae &> /1/ximm_tmp/cut/logs/xae.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaf &> /1/ximm_tmp/cut/logs/xaf.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xag &> /1/ximm_tmp/cut/logs/xag.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xah &> /1/ximm_tmp/cut/logs/xah.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xai &> /1/ximm_tmp/cut/logs/xai.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaj &> /1/ximm_tmp/cut/logs/xaj.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xak &> /1/ximm_tmp/cut/logs/xak.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xal &> /1/ximm_tmp/cut/logs/xal.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xam &> /1/ximm_tmp/cut/logs/xam.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xan &> /1/ximm_tmp/cut/logs/xan.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xao &> /1/ximm_tmp/cut/logs/xao.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xap &> /1/ximm_tmp/cut/logs/xap.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaq &> /1/ximm_tmp/cut/logs/xaq.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xar &> /1/ximm_tmp/cut/logs/xar.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xas &> /1/ximm_tmp/cut/logs/xas.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xat &> /1/ximm_tmp/cut/logs/xat.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xau &> /1/ximm_tmp/cut/logs/xau.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xav &> /1/ximm_tmp/cut/logs/xav.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaw &> /1/ximm_tmp/cut/logs/xaw.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xax &> /1/ximm_tmp/cut/logs/xax.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xay &> /1/ximm_tmp/cut/logs/xay.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xaz &> /1/ximm_tmp/cut/logs/xaz.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xba &> /1/ximm_tmp/cut/logs/xba.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbb &> /1/ximm_tmp/cut/logs/xbb.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbc &> /1/ximm_tmp/cut/logs/xbc.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbd &> /1/ximm_tmp/cut/logs/xbd.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbe &> /1/ximm_tmp/cut/logs/xbe.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbf &> /1/ximm_tmp/cut/logs/xbf.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbg &> /1/ximm_tmp/cut/logs/xbg.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbh &> /1/ximm_tmp/cut/logs/xbh.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbi &> /1/ximm_tmp/cut/logs/xbi.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbj &> /1/ximm_tmp/cut/logs/xbj.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbk &> /1/ximm_tmp/cut/logs/xbk.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbl &> /1/ximm_tmp/cut/logs/xbl.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbm &> /1/ximm_tmp/cut/logs/xbm.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbn &> /1/ximm_tmp/cut/logs/xbn.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbo &> /1/ximm_tmp/cut/logs/xbo.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbp &> /1/ximm_tmp/cut/logs/xbp.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=500000 --ldpath=/1/ximm_tmp/cut/xbq &> /1/ximm_tmp/cut/logs/xbq.log &
php /home/ximm/projects/search/listerine/es_indexer.php --postlines=377478 --ldpath=/1/ximm_tmp/cut/xbr &> /1/ximm_tmp/cut/logs/xbr.log &
ps fauxwww | grep /home/ximm/projects/search/listerine/es_indexer.php
