php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xal &> /1/ximm_tmp/cut/logs/xal.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xam &> /1/ximm_tmp/cut/logs/xam.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xan &> /1/ximm_tmp/cut/logs/xan.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xao &> /1/ximm_tmp/cut/logs/xao.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xap &> /1/ximm_tmp/cut/logs/xap.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xaq &> /1/ximm_tmp/cut/logs/xaq.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xar &> /1/ximm_tmp/cut/logs/xar.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xas &> /1/ximm_tmp/cut/logs/xas.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xat &> /1/ximm_tmp/cut/logs/xat.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xau &> /1/ximm_tmp/cut/logs/xau.log &
php es_indexer.php --postlines=900000 --ldpath=/1/ximm_tmp/cut/xav &> /1/ximm_tmp/cut/logs/xav.log &
